# Cloudflare Pages 部署配置文件
# 配置：https://developers.cloudflare.com/pages/platform/build-configuration

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# 设置环境变量（会覆盖.env.production中的值）
[build.environment.production]
  NODE_ENV = "production"
  # 部署后请在 Cloudflare Pages 仪表盘中设置 API_URL 环境变量
  # API_URL = "https://code-review-agent.workers.dev"

# 404页面处理
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
